apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "avalier-test4.fullname" . }}
  labels:
    app: {{ include "avalier-test4.fullname" . }}
    {{- include "avalier-test4.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "avalier-test4.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "avalier-test4.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          ports:
            - name: https
              containerPort: 5001
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 5000
          # readinessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 5000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: DOMAIN
            value: "avalier-test4.beta.avalier.io"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
